travis:
  secure:
    BINSTAR_TOKEN: Ye0zf8qqZJokWU/QT5M/8c94VotvnyGcaK5mSpRtVGBvVGheLAV4M1JW3nqImj5EypjWubqp47fEEclbaF0Dxx1yZ5hd1/K85qxNW3vlsTYBwWzCzsmuuG678flyfT+llyBmkwJSx8Nq9aUG8M9uASbSnBZNSHtY0r15ujPaSm00tU/QjClNEk+San0vBih3ISKt9WoOWDiKkTqr3bI6kugop8STqtPANHIC+PiPC8KtUFez9yB8dm+zK6858sKxjlhqiul+5+86apRdXoUOfLCv1s4wqdl0tFW/lCz7ZZnQrxMInykPKwBBUD1/ZnD9/gXuoJ+/FeL2HFjQ3+lV62zqJmNN3X3VdeRQfpLzXI35hAswtvGPIxaGsCGYk5o8iycud/xjTdKJEmSUsoq+Dg2o1J6V3DLww0dVRUw0iMg9nJgCq1tb4N06AaLcfr86OFrn1Wj6qjbS9w53aguxgSBjV0cKVRR7tGDet/M/GNTzQnej0dhBB5k6QALrKBOeTQG1W0/Tj0lWQuwcPPZO5R4fGmpxHm4obPE0CIQtC3USewJJ0Iqp7G/GqORlD+0TKFHEfNBhfLTLMPOS4NUOUc9wDnqU9v7Tvskk/Oy8PCMeNzQSRS1FqbiOu+3QBNH/UzTTKC3Yh5uB50KfE67W8AB79P8HcipNTCFqrRD5to8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
