travis:
  secure:
    BINSTAR_TOKEN: N9XJ3dDUI8Tov8hXL3ppQTv4Zwt+1oP9kiK7TkOclowT8CVN1EA6d5m3OAm3+7pj4BEkI2CJZJP+5xKCjLDiniO7SAJ+pQjOIjJ8dOZUu0yxVKxWle7czWun9Q0/KLGjZZO87XQHYTCJdQNAYMD9O9ySjS2AD/e0pONqgeD9Um2KozEsdjn7z+A/4LwJwf3yNpr1PJlXhE4qdHKUPz67Clo9w6zdQGJtOLE3m8y0Utb+3mW66v1G2Wq/ltQPRRhfLv9OP50a3m1lX4qVLzr45ZzEiMPwL6pD492cdhWZTxMbcFbfiamK+JpEtaVmNTfmqYR4k7Pl6dUirnQT77p8g57iJvYQ76qzfntPzpquR5+/C4cMkF8Xes0LFt+/U1h9TF+ZAjeO9hPVP5SFD2zmvPCERa0ssH736Ww7iBz3zbUlnBzBh8nuJQoHZ6EuLWX/oDXvpzOQb8CBD+JtRMR764BmdzuaTynPNwT70YotZpsz2mgrOOGof4Ie2QAVYq8SD1jevcfmy5JGFxel1Yg0COayn2He2eIv+qv4yHgu3NLwVnv1CXkceOw2jBeMwGtc9Yf91yLIi2VJr92FnOFq6+BgzbNf9wXVzuyVndjHgJVhIEiVPXTP6vW5HWFlTEb1B+s321tWljPVCD43FJRTRNEVJ8DllZN3lBXtRvPSfJ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
